In [1]:
!pip3 install convokit
!python3 -m spacy download en_core_web_sm

import pandas as pd
import nltk

from convokit import Corpus, download

Requirement already satisfied: convokit in /Users/quinn/opt/anaconda3/envs/pp275/lib/python3.9/site-packages (2.5.3)
Requirement already satisfied: scikit-learn>=0.20.0 in /Users/quinn/opt/anaconda3/envs/pp275/lib/python3.9/site-packages (from convokit) (1.1.2)
Requirement already satisfied: matplotlib>=3.0.0 in /Users/quinn/opt/anaconda3/envs/pp275/lib/python3.9/site-packages (from convokit) (3.5.3)
Requirement already satisfied: scipy>=1.1.0 in /Users/quinn/opt/anaconda3/envs/pp275/lib/python3.9/site-packages (from convokit) (1.9.0)
Requirement already satisfied: dill>=0.2.9 in /Users/quinn/opt/anaconda3/envs/pp275/lib/python3.9/site-packages (from convokit) (0.3.6)
Requirement already satisfied: joblib>=0.13.2 in /Users/quinn/opt/anaconda3/envs/pp275/lib/python3.9/site-packages (from convokit) (1.1.0)
Requirement already satisfied: pandas>=0.23.4 in /Users/quinn/opt/anaconda3/envs/pp275/lib/python3.9/site-packages (from convokit) (1.4.3)
Requirement already satisfied: clean-text>=0.1.1 in /Users/quinn/opt/anaconda3/envs/pp275/lib/python3.9/site-packages (from convokit) (0.6.0)
Requirement already satisfied: msgpack-numpy>=0.4.3.2 in /Users/quinn/opt/anaconda3/envs/pp275/lib/python3.9/site-packages (from convokit) (0.4.8)
Requirement already satisfied: spacy>=2.3.5 in /Users/quinn/opt/anaconda3/envs/pp275/lib/python3.9/site-packages (from convokit) (3.5.2)
Requirement already satisfied: unidecode>=1.1.1 in /Users/quinn/opt/anaconda3/envs/pp275/lib/python3.9/site-packages (from convokit) (1.3.6)
Requirement already satisfied: nltk>=3.4 in /Users/quinn/opt/anaconda3/envs/pp275/lib/python3.9/site-packages (from convokit) (3.8.1)
Requirement already satisfied: emoji<2.0.0,>=1.0.0 in /Users/quinn/opt/anaconda3/envs/pp275/lib/python3.9/site-packages (from clean-text>=0.1.1->convokit) (1.7.0)
Requirement already satisfied: ftfy<7.0,>=6.0 in /Users/quinn/opt/anaconda3/envs/pp275/lib/python3.9/site-packages (from clean-text>=0.1.1->convokit) (6.1.1)
Requirement already satisfied: pillow>=6.2.0 in /Users/quinn/opt/anaconda3/envs/pp275/lib/python3.9/site-packages (from matplotlib>=3.0.0->convokit) (9.2.0)
Requirement already satisfied: cycler>=0.10 in /Users/quinn/opt/anaconda3/envs/pp275/lib/python3.9/site-packages (from matplotlib>=3.0.0->convokit) (0.11.0)
Requirement already satisfied: packaging>=20.0 in /Users/quinn/opt/anaconda3/envs/pp275/lib/python3.9/site-packages (from matplotlib>=3.0.0->convokit) (21.3)
Requirement already satisfied: kiwisolver>=1.0.1 in /Users/quinn/opt/anaconda3/envs/pp275/lib/python3.9/site-packages (from matplotlib>=3.0.0->convokit) (1.4.4)
Requirement already satisfied: numpy>=1.17 in /Users/quinn/opt/anaconda3/envs/pp275/lib/python3.9/site-packages (from matplotlib>=3.0.0->convokit) (1.23.2)
Requirement already satisfied: python-dateutil>=2.7 in /Users/quinn/opt/anaconda3/envs/pp275/lib/python3.9/site-packages (from matplotlib>=3.0.0->convokit) (2.8.2)
Requirement already satisfied: fonttools>=4.22.0 in /Users/quinn/opt/anaconda3/envs/pp275/lib/python3.9/site-packages (from matplotlib>=3.0.0->convokit) (4.37.1)
Requirement already satisfied: pyparsing>=2.2.1 in /Users/quinn/opt/anaconda3/envs/pp275/lib/python3.9/site-packages (from matplotlib>=3.0.0->convokit) (3.0.9)
Requirement already satisfied: msgpack>=0.5.2 in /Users/quinn/opt/anaconda3/envs/pp275/lib/python3.9/site-packages (from msgpack-numpy>=0.4.3.2->convokit) (1.0.5)
Requirement already satisfied: regex>=2021.8.3 in /Users/quinn/opt/anaconda3/envs/pp275/lib/python3.9/site-packages (from nltk>=3.4->convokit) (2023.3.23)
Requirement already satisfied: click in /Users/quinn/opt/anaconda3/envs/pp275/lib/python3.9/site-packages (from nltk>=3.4->convokit) (8.1.3)
Requirement already satisfied: tqdm in /Users/quinn/opt/anaconda3/envs/pp275/lib/python3.9/site-packages (from nltk>=3.4->convokit) (4.64.0)
Requirement already satisfied: pytz>=2020.1 in /Users/quinn/opt/anaconda3/envs/pp275/lib/python3.9/site-packages (from pandas>=0.23.4->convokit) (2022.2.1)
Requirement already satisfied: threadpoolctl>=2.0.0 in /Users/quinn/opt/anaconda3/envs/pp275/lib/python3.9/site-packages (from scikit-learn>=0.20.0->convokit) (3.1.0)
Requirement already satisfied: pathy>=0.10.0 in /Users/quinn/opt/anaconda3/envs/pp275/lib/python3.9/site-packages (from spacy>=2.3.5->convokit) (0.10.1)
Requirement already satisfied: jinja2 in /Users/quinn/opt/anaconda3/envs/pp275/lib/python3.9/site-packages (from spacy>=2.3.5->convokit) (3.1.2)
Requirement already satisfied: murmurhash<1.1.0,>=0.28.0 in /Users/quinn/opt/anaconda3/envs/pp275/lib/python3.9/site-packages (from spacy>=2.3.5->convokit) (1.0.9)
Requirement already satisfied: preshed<3.1.0,>=3.0.2 in /Users/quinn/opt/anaconda3/envs/pp275/lib/python3.9/site-packages (from spacy>=2.3.5->convokit) (3.0.8)
Requirement already satisfied: smart-open<7.0.0,>=5.2.1 in /Users/quinn/opt/anaconda3/envs/pp275/lib/python3.9/site-packages (from spacy>=2.3.5->convokit) (6.3.0)
Requirement already satisfied: cymem<2.1.0,>=2.0.2 in /Users/quinn/opt/anaconda3/envs/pp275/lib/python3.9/site-packages (from spacy>=2.3.5->convokit) (2.0.7)
Requirement already satisfied: pydantic!=1.8,!=1.8.1,<1.11.0,>=1.7.4 in /Users/quinn/opt/anaconda3/envs/pp275/lib/python3.9/site-packages (from spacy>=2.3.5->convokit) (1.10.7)
Requirement already satisfied: srsly<3.0.0,>=2.4.3 in /Users/quinn/opt/anaconda3/envs/pp275/lib/python3.9/site-packages (from spacy>=2.3.5->convokit) (2.4.6)
Requirement already satisfied: spacy-loggers<2.0.0,>=1.0.0 in /Users/quinn/opt/anaconda3/envs/pp275/lib/python3.9/site-packages (from spacy>=2.3.5->convokit) (1.0.4)
Requirement already satisfied: langcodes<4.0.0,>=3.2.0 in /Users/quinn/opt/anaconda3/envs/pp275/lib/python3.9/site-packages (from spacy>=2.3.5->convokit) (3.3.0)
Requirement already satisfied: setuptools in /Users/quinn/opt/anaconda3/envs/pp275/lib/python3.9/site-packages (from spacy>=2.3.5->convokit) (65.3.0)
Requirement already satisfied: wasabi<1.2.0,>=0.9.1 in /Users/quinn/opt/anaconda3/envs/pp275/lib/python3.9/site-packages (from spacy>=2.3.5->convokit) (1.1.1)
Requirement already satisfied: thinc<8.2.0,>=8.1.8 in /Users/quinn/opt/anaconda3/envs/pp275/lib/python3.9/site-packages (from spacy>=2.3.5->convokit) (8.1.9)
Requirement already satisfied: spacy-legacy<3.1.0,>=3.0.11 in /Users/quinn/opt/anaconda3/envs/pp275/lib/python3.9/site-packages (from spacy>=2.3.5->convokit) (3.0.12)
Requirement already satisfied: requests<3.0.0,>=2.13.0 in /Users/quinn/opt/anaconda3/envs/pp275/lib/python3.9/site-packages (from spacy>=2.3.5->convokit) (2.28.1)
Requirement already satisfied: typer<0.8.0,>=0.3.0 in /Users/quinn/opt/anaconda3/envs/pp275/lib/python3.9/site-packages (from spacy>=2.3.5->convokit) (0.7.0)
Requirement already satisfied: catalogue<2.1.0,>=2.0.6 in /Users/quinn/opt/anaconda3/envs/pp275/lib/python3.9/site-packages (from spacy>=2.3.5->convokit) (2.0.8)
Requirement already satisfied: wcwidth>=0.2.5 in /Users/quinn/opt/anaconda3/envs/pp275/lib/python3.9/site-packages (from ftfy<7.0,>=6.0->clean-text>=0.1.1->convokit) (0.2.5)
Requirement already satisfied: typing-extensions>=4.2.0 in /Users/quinn/opt/anaconda3/envs/pp275/lib/python3.9/site-packages (from pydantic!=1.8,!=1.8.1,<1.11.0,>=1.7.4->spacy>=2.3.5->convokit) (4.5.0)
Requirement already satisfied: six>=1.5 in /Users/quinn/opt/anaconda3/envs/pp275/lib/python3.9/site-packages (from python-dateutil>=2.7->matplotlib>=3.0.0->convokit) (1.16.0)
Requirement already satisfied: urllib3<1.27,>=1.21.1 in /Users/quinn/opt/anaconda3/envs/pp275/lib/python3.9/site-packages (from requests<3.0.0,>=2.13.0->spacy>=2.3.5->convokit) (1.26.11)
Requirement already satisfied: charset-normalizer<3,>=2 in /Users/quinn/opt/anaconda3/envs/pp275/lib/python3.9/site-packages (from requests<3.0.0,>=2.13.0->spacy>=2.3.5->convokit) (2.1.1)
Requirement already satisfied: idna<4,>=2.5 in /Users/quinn/opt/anaconda3/envs/pp275/lib/python3.9/site-packages (from requests<3.0.0,>=2.13.0->spacy>=2.3.5->convokit) (3.3)
Requirement already satisfied: certifi>=2017.4.17 in /Users/quinn/opt/anaconda3/envs/pp275/lib/python3.9/site-packages (from requests<3.0.0,>=2.13.0->spacy>=2.3.5->convokit) (2022.12.7)
Requirement already satisfied: confection<1.0.0,>=0.0.1 in /Users/quinn/opt/anaconda3/envs/pp275/lib/python3.9/site-packages (from thinc<8.2.0,>=8.1.8->spacy>=2.3.5->convokit) (0.0.4)
Requirement already satisfied: blis<0.8.0,>=0.7.8 in /Users/quinn/opt/anaconda3/envs/pp275/lib/python3.9/site-packages (from thinc<8.2.0,>=8.1.8->spacy>=2.3.5->convokit) (0.7.9)

Requirement already satisfied: MarkupSafe>=2.0 in /Users/quinn/opt/anaconda3/envs/pp275/lib/python3.9/site-packages (from jinja2->spacy>=2.3.5->convokit) (2.1.1)
Collecting en-core-web-sm==3.5.0
  Downloading https://github.com/explosion/spacy-models/releases/download/en_core_web_sm-3.5.0/en_core_web_sm-3.5.0-py3-none-any.whl (12.8 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 12.8/12.8 MB 8.8 MB/s eta 0:00:0000:0100:01
Requirement already satisfied: spacy<3.6.0,>=3.5.0 in /Users/quinn/opt/anaconda3/envs/pp275/lib/python3.9/site-packages (from en-core-web-sm==3.5.0) (3.5.2)
Requirement already satisfied: numpy>=1.15.0 in /Users/quinn/opt/anaconda3/envs/pp275/lib/python3.9/site-packages (from spacy<3.6.0,>=3.5.0->en-core-web-sm==3.5.0) (1.23.2)
Requirement already satisfied: murmurhash<1.1.0,>=0.28.0 in /Users/quinn/opt/anaconda3/envs/pp275/lib/python3.9/site-packages (from spacy<3.6.0,>=3.5.0->en-core-web-sm==3.5.0) (1.0.9)
Requirement already satisfied: jinja2 in /Users/quinn/opt/anaconda3/envs/pp275/lib/python3.9/site-packages (from spacy<3.6.0,>=3.5.0->en-core-web-sm==3.5.0) (3.1.2)
Requirement already satisfied: requests<3.0.0,>=2.13.0 in /Users/quinn/opt/anaconda3/envs/pp275/lib/python3.9/site-packages (from spacy<3.6.0,>=3.5.0->en-core-web-sm==3.5.0) (2.28.1)
Requirement already satisfied: preshed<3.1.0,>=3.0.2 in /Users/quinn/opt/anaconda3/envs/pp275/lib/python3.9/site-packages (from spacy<3.6.0,>=3.5.0->en-core-web-sm==3.5.0) (3.0.8)
Requirement already satisfied: typer<0.8.0,>=0.3.0 in /Users/quinn/opt/anaconda3/envs/pp275/lib/python3.9/site-packages (from spacy<3.6.0,>=3.5.0->en-core-web-sm==3.5.0) (0.7.0)
Requirement already satisfied: pathy>=0.10.0 in /Users/quinn/opt/anaconda3/envs/pp275/lib/python3.9/site-packages (from spacy<3.6.0,>=3.5.0->en-core-web-sm==3.5.0) (0.10.1)
Requirement already satisfied: srsly<3.0.0,>=2.4.3 in /Users/quinn/opt/anaconda3/envs/pp275/lib/python3.9/site-packages (from spacy<3.6.0,>=3.5.0->en-core-web-sm==3.5.0) (2.4.6)
Requirement already satisfied: tqdm<5.0.0,>=4.38.0 in /Users/quinn/opt/anaconda3/envs/pp275/lib/python3.9/site-packages (from spacy<3.6.0,>=3.5.0->en-core-web-sm==3.5.0) (4.64.0)
Requirement already satisfied: packaging>=20.0 in /Users/quinn/opt/anaconda3/envs/pp275/lib/python3.9/site-packages (from spacy<3.6.0,>=3.5.0->en-core-web-sm==3.5.0) (21.3)
Requirement already satisfied: smart-open<7.0.0,>=5.2.1 in /Users/quinn/opt/anaconda3/envs/pp275/lib/python3.9/site-packages (from spacy<3.6.0,>=3.5.0->en-core-web-sm==3.5.0) (6.3.0)
Requirement already satisfied: thinc<8.2.0,>=8.1.8 in /Users/quinn/opt/anaconda3/envs/pp275/lib/python3.9/site-packages (from spacy<3.6.0,>=3.5.0->en-core-web-sm==3.5.0) (8.1.9)
Requirement already satisfied: wasabi<1.2.0,>=0.9.1 in /Users/quinn/opt/anaconda3/envs/pp275/lib/python3.9/site-packages (from spacy<3.6.0,>=3.5.0->en-core-web-sm==3.5.0) (1.1.1)
Requirement already satisfied: setuptools in /Users/quinn/opt/anaconda3/envs/pp275/lib/python3.9/site-packages (from spacy<3.6.0,>=3.5.0->en-core-web-sm==3.5.0) (65.3.0)
Requirement already satisfied: cymem<2.1.0,>=2.0.2 in /Users/quinn/opt/anaconda3/envs/pp275/lib/python3.9/site-packages (from spacy<3.6.0,>=3.5.0->en-core-web-sm==3.5.0) (2.0.7)
Requirement already satisfied: catalogue<2.1.0,>=2.0.6 in /Users/quinn/opt/anaconda3/envs/pp275/lib/python3.9/site-packages (from spacy<3.6.0,>=3.5.0->en-core-web-sm==3.5.0) (2.0.8)
Requirement already satisfied: langcodes<4.0.0,>=3.2.0 in /Users/quinn/opt/anaconda3/envs/pp275/lib/python3.9/site-packages (from spacy<3.6.0,>=3.5.0->en-core-web-sm==3.5.0) (3.3.0)
Requirement already satisfied: pydantic!=1.8,!=1.8.1,<1.11.0,>=1.7.4 in /Users/quinn/opt/anaconda3/envs/pp275/lib/python3.9/site-packages (from spacy<3.6.0,>=3.5.0->en-core-web-sm==3.5.0) (1.10.7)
Requirement already satisfied: spacy-loggers<2.0.0,>=1.0.0 in /Users/quinn/opt/anaconda3/envs/pp275/lib/python3.9/site-packages (from spacy<3.6.0,>=3.5.0->en-core-web-sm==3.5.0) (1.0.4)
Requirement already satisfied: spacy-legacy<3.1.0,>=3.0.11 in /Users/quinn/opt/anaconda3/envs/pp275/lib/python3.9/site-packages (from spacy<3.6.0,>=3.5.0->en-core-web-sm==3.5.0) (3.0.12)
Requirement already satisfied: pyparsing!=3.0.5,>=2.0.2 in /Users/quinn/opt/anaconda3/envs/pp275/lib/python3.9/site-packages (from packaging>=20.0->spacy<3.6.0,>=3.5.0->en-core-web-sm==3.5.0) (3.0.9)
Requirement already satisfied: typing-extensions>=4.2.0 in /Users/quinn/opt/anaconda3/envs/pp275/lib/python3.9/site-packages (from pydantic!=1.8,!=1.8.1,<1.11.0,>=1.7.4->spacy<3.6.0,>=3.5.0->en-core-web-sm==3.5.0) (4.5.0)
Requirement already satisfied: idna<4,>=2.5 in /Users/quinn/opt/anaconda3/envs/pp275/lib/python3.9/site-packages (from requests<3.0.0,>=2.13.0->spacy<3.6.0,>=3.5.0->en-core-web-sm==3.5.0) (3.3)
Requirement already satisfied: certifi>=2017.4.17 in /Users/quinn/opt/anaconda3/envs/pp275/lib/python3.9/site-packages (from requests<3.0.0,>=2.13.0->spacy<3.6.0,>=3.5.0->en-core-web-sm==3.5.0) (2022.12.7)
Requirement already satisfied: urllib3<1.27,>=1.21.1 in /Users/quinn/opt/anaconda3/envs/pp275/lib/python3.9/site-packages (from requests<3.0.0,>=2.13.0->spacy<3.6.0,>=3.5.0->en-core-web-sm==3.5.0) (1.26.11)
Requirement already satisfied: charset-normalizer<3,>=2 in /Users/quinn/opt/anaconda3/envs/pp275/lib/python3.9/site-packages (from requests<3.0.0,>=2.13.0->spacy<3.6.0,>=3.5.0->en-core-web-sm==3.5.0) (2.1.1)
Requirement already satisfied: confection<1.0.0,>=0.0.1 in /Users/quinn/opt/anaconda3/envs/pp275/lib/python3.9/site-packages (from thinc<8.2.0,>=8.1.8->spacy<3.6.0,>=3.5.0->en-core-web-sm==3.5.0) (0.0.4)
Requirement already satisfied: blis<0.8.0,>=0.7.8 in /Users/quinn/opt/anaconda3/envs/pp275/lib/python3.9/site-packages (from thinc<8.2.0,>=8.1.8->spacy<3.6.0,>=3.5.0->en-core-web-sm==3.5.0) (0.7.9)
Requirement already satisfied: click<9.0.0,>=7.1.1 in /Users/quinn/opt/anaconda3/envs/pp275/lib/python3.9/site-packages (from typer<0.8.0,>=0.3.0->spacy<3.6.0,>=3.5.0->en-core-web-sm==3.5.0) (8.1.3)
Requirement already satisfied: MarkupSafe>=2.0 in /Users/quinn/opt/anaconda3/envs/pp275/lib/python3.9/site-packages (from jinja2->spacy<3.6.0,>=3.5.0->en-core-web-sm==3.5.0) (2.1.1)
✔ Download and installation successful
You can now load the package via spacy.load('en_core_web_sm')

In [3]:
Corpus?

In [4]:
# replace with Corpus(filename=download("supreme-corpus"))
corpus = Corpus(filename='/Users/quinn/.convokit/downloads/supreme-corpus')

In [5]:
utt_ids = corpus.get_utterance_ids()
transcript = corpus.get_utterance(utt_ids[100])

In [6]:
# use basic dataframe cause why not
df = corpus.get_conversations_dataframe()

df.head()

,vectors,meta.case_id,meta.advocates,meta.win_side,meta.votes_side
id,,,,,
13127,[],1955_71,"{'harry_f_murphy': {'side': 1, 'role': 'inferr...",0,"{'j__john_m_harlan2': 0, 'j__hugo_l_black': 0,..."
12997,[],1955_410,"{'howard_c_westwood': {'side': 1, 'role': 'inf...",1,"{'j__john_m_harlan2': 1, 'j__hugo_l_black': 1,..."
13024,[],1955_410,"{'howard_c_westwood': {'side': 1, 'role': 'inf...",1,"{'j__john_m_harlan2': 1, 'j__hugo_l_black': 1,..."
13015,[],1955_351,"{'harry_d_graham': {'side': 3, 'role': 'inferr...",1,"{'j__john_m_harlan2': 1, 'j__hugo_l_black': 1,..."
13016,[],1955_38,"{'robert_n_gorman': {'side': 3, 'role': 'infer...",0,"{'j__john_m_harlan2': 0, 'j__hugo_l_black': 0,..."

In [7]:
# get_transcript(df.id[0])
df['convo_id'] = df.index

In [8]:
df = df.reset_index().drop(['id'], axis=1)

In [9]:
df['term_year'] = [case_id.split('_')[0] for case_id in df['meta.case_id']]
df['docket_id'] = [case_id.split('_')[1] for case_id in df['meta.case_id']]
df.head(-5)

,vectors,meta.case_id,meta.advocates,meta.win_side,meta.votes_side,convo_id,term_year,docket_id
0,[],1955_71,"{'harry_f_murphy': {'side': 1, 'role': 'inferr...",0,"{'j__john_m_harlan2': 0, 'j__hugo_l_black': 0,...",13127,1955,71
1,[],1955_410,"{'howard_c_westwood': {'side': 1, 'role': 'inf...",1,"{'j__john_m_harlan2': 1, 'j__hugo_l_black': 1,...",12997,1955,410
2,[],1955_410,"{'howard_c_westwood': {'side': 1, 'role': 'inf...",1,"{'j__john_m_harlan2': 1, 'j__hugo_l_black': 1,...",13024,1955,410
3,[],1955_351,"{'harry_d_graham': {'side': 3, 'role': 'inferr...",1,"{'j__john_m_harlan2': 1, 'j__hugo_l_black': 1,...",13015,1955,351
4,[],1955_38,"{'robert_n_gorman': {'side': 3, 'role': 'infer...",0,"{'j__john_m_harlan2': 0, 'j__hugo_l_black': 0,...",13016,1955,38
...,...,...,...,...,...,...,...,...
7807,[],2019_19-7,"{'kannon_k_shanmugam': {'side': 1, 'role': 'fo...",1,"{'j__john_g_roberts_jr': 1, 'j__clarence_thoma...",24977,2019,19-7
7808,[],2019_18-6662,"{'richard_m_summa': {'side': 1, 'role': 'for t...",0,"{'j__john_g_roberts_jr': 0, 'j__clarence_thoma...",24968,2019,18-6662
7809,[],2019_17-1712,"{'peter_k_stris': {'side': 1, 'role': 'for the...",0,"{'j__john_g_roberts_jr': 0, 'j__clarence_thoma...",24959,2019,17-1712
7810,[],2019_18-916,"{'adam_h_charnes': {'side': 1, 'role': 'for th...",1,"{'j__john_g_roberts_jr': 1, 'j__clarence_thoma...",24954,2019,18-916
7811,[],2019_19-715,"{'patrick_strawbridge': {'side': 1, 'role': 'f...",1,"{'j__john_g_roberts_jr': 1, 'j__clarence_thoma...",25000,2019,19-715

In [57]:
df.loc[df.duplicated(subset=['meta.case_id'])][1000:]  # 1961_8 can be a test case_id

,vectors,meta.case_id,meta.advocates,meta.win_side,meta.votes_side,convo_id,term_year,docket_id
3694,[],1977_77-528,"{'louis_f_claiborne': {'side': 0, 'role': 'Arg...",1,"{'j__potter_stewart': 0, 'j__thurgood_marshall...",17715,1977,77-528
3728,[],1977_76-1726,"{'carl_j_schumacher': {'side': 1, 'role': 'for...",1,"{'j__potter_stewart': 1, 'j__thurgood_marshall...",16777,1977,76-1726
3743,[],1977_75-1690,"{'r_douglas_lackey': {'side': 1, 'role': 'for ...",1,"{'j__potter_stewart': 1, 'j__thurgood_marshall...",17694,1977,75-1690
3752,[],1977_76-558,"{'john_h_lederer': {'side': 1, 'role': 'for ap...",1,"{'j__potter_stewart': 1, 'j__thurgood_marshall...",17216,1977,76-558
3760,[],1977_76-1607,"{'harvey_l_pitt': {'side': 1, 'role': 'for pet...",0,"{'j__potter_stewart': 0, 'j__thurgood_marshall...",17403,1977,76-1607
...,...,...,...,...,...,...,...,...
7470,[],2014_14-556,"{'mary_l_bonauto': {'side': 1, 'role': 'for th...",1,"{'j__john_g_roberts_jr': 0, 'j__antonin_scalia...",23753,2014,14-556
7521,[],2015_14-449,"{'stephen_r_mcallister': {'side': 1, 'role': '...",1,"{'j__john_g_roberts_jr': 1, 'j__antonin_scalia...",24000,2015,14-449
7651,[],2017_15-1204,"{'malcolm_l_stewart': {'side': 1, 'role': 'for...",1,"{'j__john_g_roberts_jr': 1, 'j__anthony_m_kenn...",24575,2017,15-1204
7675,[],2017_15-1498,"{'edwin_s_kneedler': {'side': 1, 'role': 'for ...",0,"{'j__john_g_roberts_jr': 1, 'j__anthony_m_kenn...",24593,2017,15-1498
7717,[],2018_17-647,"{'j_david_breemer': {'side': 1, 'role': 'for p...",1,"{'j__john_g_roberts_jr': 1, 'j__clarence_thoma...",24794,2018,17-647

In [35]:
def get_transcript(convo_id, remove_return=False):

  # pull conversation object
  convo = corpus.get_conversation(convo_id)

  # from conversation object, create list of utterance (i.e. the text bits) ids
  convo_utts = list(convo.iter_utterances())
  
  # combine text data from all utterances 
  if remove_return:
    convo_transcript = [utt.text.replace('\n', ' ') for utt in convo_utts]
  else:
    convo_transcript = [utt.text for utt in convo_utts]

  # join elements of list 
  convo_transcript = ''.join(convo_transcript)
  
  return convo_transcript

In [56]:
get_transcript('13024') # William A. Price, Petitioner, versus United States

"Number 410, American Airlines, Incorporated versus North American Airlines, Incorporated.\nMr. Westwood.May it please the Court.\nThis case is here on certiorari to the Court of Appeals for the District of Columbia Circuit.\nThat Court reversed an order entered by the Civil Aeronautics Board.\nThe Civil Aeronautics Act provides for judicial review of C.A.B. orders by Courts Of Appeals.\nThe order of the Civil Aeronautics Board was entered on -- against the respondent here, North American Airlines, under Section 411 of the Civil Aeronautics Act.\nSection 411 is set forth at the bottom of page 3 of our brief.\nOur brief is the -- the yellow cover.\nThat Section provides that the Board, may either on its own initiative or on complaint by an air carrier, if it considers that such action by it would be in the interest of the public, investigate and determine whether an air carrier has been or is engaged in an unfair or deceptive practice or unfair method of competition.\nThen, if after notice and hearing it is found that that -- that an air carrier has been engaged in such practice or method of competition, it is provided that the Board shall order the carrier to cease and desist therefrom.\nPreliminarily, I should say that Section 411 appears in the context of an elaborate regulation of common carriers by air, the Civil Aeronautics Act, which is modeled generally on Titles 1 and 2 of the Interstate Commerce Act and which is administered by the Civil Aeronautics Board.\nNow, Section 411 as Your Honors will recognize is generally similar to Section 5 of the Federal Trade Commission Act.\nSection 5 of the Federal Trade Commission Act is set forth in pertinent part in the footnote on page 4 of our brief.\nNow, the case arose before the Civil Aeronautics Board in this way.\nThe respondent, North American Airlines, is a common carrier by air as is the petitioner, American Airlines, both subject to the Civil Aeronautics Act.\nThe respondent had operating authority issued by the Civil Aeronautics Board in the name in which it -- which it formally held, that is Twentieth Century Airlines, authority issued to it in that name back about 1947.\nAbout four years later, the respondent began using the fictitious name North American Airlines.\nAbout a year after that in 1952, it advised -- it changed its name formally to North American Airlines, advised the Civil Aeronautics Board of the change in name and suggested that its operating authority should be amended accordingly from Twentieth Century to North American Airlines.\nNow, pursuant to a procedure, which is described in our briefs and which I shan't go into here, the petitioner, American Airlines, filed with the Civil Aeronautics Board a memorandum complaining that the adoption by the respondent of the name North American Airlines was causing the public to become seriously confused as to the identity of American Airlines and North American and misleading the public into the belief that North American was the same as American Airlines.\nAnd in the memorandum it was pointed out as, of course, the Board knew that the two carriers in fact did compete directly on one of the principal air routes of the nation that is between New York, Chicago and Los Angeles.\nAffidavits were submitted by the -- by American Airlines, the petitioner here, in support of its memorandum filed with the Board.\nThe Board considered the matter and then entered an order instituting a proceeding under Section 411 and set the matter down for hearing to determine whether the respondent in engaging in air transportation under the name North American was engaged in an unfair practice or unfair method of competition because of the confusion caused to the public.\nThe matter was set for hearing by the Board before one of its examiners.\nThe petitioner here, American, became a party to the proceeding.\nNumerous witnesses were heard, some 16 in all and there was received by the examiner at the hearing also documentary evidence and by stipulation of the parties other documentary records of the Board were incorporated into the record.\nIn due course, the examiner rendered his initial decision.\nIn that decision, he made extensive findings of fact.\nHe found that there was indeed very substantial confusion on the part of the public due to the similarity in the names between the two carriers.\nHe found that American Airlines had been operating under the name American for some 20 or 25 years, that the public had become familiar with that name and had identified when that -- the name American Airlines is used in connection with air transportation, had identified it as meaning this particular carrier and that the respondent in -- in the use of the name North American Airlines, had created a situation whereby the public was led to believe that somehow or other the two carriers were either one and the same or somehow affiliated.\nAnd he recommended that the Board enter a cease and desist order substantially in the form ultimately adopted by the Board which would require that the respondent cease engaging in air transportation under the name North American or any other name involving the use of the word American.\nExceptions were filed by the respondent.\nThe matter was briefed and argued to the Board.\nThe Board adopted many of the examiners findings, which indeed were set forth as an appendix to its opinion and made additional findings of fact of its own, which in the main were directed to various exceptions that the respondent had filed with the Board.\nThe -- those findings bring out the facts, some of -- most of which had been dealt with by the examiner that there was a constant stream of people coming up to ticket offices thinking that the two carriers were the same, trying to check-in with the wrong carrier as a result of the similarity of names, people meeting airplanes at the wrong place, people calling the wrong carrier for reservations, people claiming baggage at the wrong counter and so forth.Is -- is there another company in the name North American?No, there were just the -- just the two, North American and American.North American Aviation is different then?Well, that -- that is a -- that is a manufacturer of aircraft, yes, Your Honor.\nThe --They don't -- they don't operate any plane?No, Your Honor.\nThe findings elaborated on the confusion, pointing out that actually the confusion went beyond even the traveling public.\nFor example, a labor union having some kind of dispute or grievance against North American threatened to picket American Airlines.\nThree newspapers reporting a robbery that had occurred at North American attributed -- or stated that it had occurred at American Airlines.\nTradesmen dunned American for bills owed by North American and so on.\nIn other words, I mention that only to emphasize the fact that the confusion was extensive indeed.\nNow, the Board also, in its findings, found -- stated specifically that the public was very much concerned with this matter because the common carriers by air should be held to high standards of service and it was contrary to the interest of the public to be subjected to the kind of misleading confusion that the record showed, that the advantages of air transportation, which are speed, indeed could be defeated by the delays incident to people being misled into calling the wrong carrier and going to the wrong ticket office and so forth.\nAnd it was made very clear in the -- both in the opinion of the Board and in the findings of the examiner himself that the action which ultimately was taken, was taken on account of the Board's conception of the interest of the public in the matter and not simply to vindicate such private interest as American Airlines might or might not have in the dispute.\nAnd so, the Board entered the cease and desist order to which I have referred.\nThe respondent appealed to the Court of Appeals for the District of Columbia.\nBy a pre-hearing conference in that Court, the issues were precisely defined and limited by stipulation of the parties.\nAt this stage in the case, the only issue that really remains in the case is the first that was set forth in the stipulation, and that issue was whether the findings of the Board make out a case of violation of Section 411 of the Civil Aeronautics Act on account of the use by the respondent of the name North American Airlines.\nThe petitioner intervened in the Court of Appeals.\nThe stipulation appears at -- I had it right here -- no, it's -- I'm sorry, at page 307.We'll -- we'll adjourn now, Mr. Westwood."

In [58]:
import numpy as np

In [59]:
df.head()

,vectors,meta.case_id,meta.advocates,meta.win_side,meta.votes_side,convo_id,term_year,docket_id
0,[],1955_71,"{'harry_f_murphy': {'side': 1, 'role': 'inferr...",0,"{'j__john_m_harlan2': 0, 'j__hugo_l_black': 0,...",13127,1955,71
1,[],1955_410,"{'howard_c_westwood': {'side': 1, 'role': 'inf...",1,"{'j__john_m_harlan2': 1, 'j__hugo_l_black': 1,...",12997,1955,410
2,[],1955_410,"{'howard_c_westwood': {'side': 1, 'role': 'inf...",1,"{'j__john_m_harlan2': 1, 'j__hugo_l_black': 1,...",13024,1955,410
3,[],1955_351,"{'harry_d_graham': {'side': 3, 'role': 'inferr...",1,"{'j__john_m_harlan2': 1, 'j__hugo_l_black': 1,...",13015,1955,351
4,[],1955_38,"{'robert_n_gorman': {'side': 3, 'role': 'infer...",0,"{'j__john_m_harlan2': 0, 'j__hugo_l_black': 0,...",13016,1955,38

In [60]:
martin_quinn = pd.read_csv('MartinQuinnScores.csv')

In [61]:
martin_quinn

,term,med,med_sd,min,max,justice,just_pr,CEHughes2,JCMcReynolds,LDBrandeis,...,CThomas,RBGinsburg,SGBreyer,JGRoberts,SAAlito,SSotomayor,EKagan,NMGorsuch,BMKavanaugh,ACBarrett
0,1955,0.559,0.484,-4.166,1.348,FFrankfurter,0.774,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,1956,0.162.5,0.510,-4.670,1.322,TCClark,0.984,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,1957,0.58,0.545,-5.082,1.386,TCClark,0.951,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,1958,0.643,0.578,-5.457,1.643,TCClark,0.492,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,1959,0.335,0.621,-5.759,1.846,TCClark,0.870,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
62,2017,0.298,0.501,-3.720,3.131,AMKennedy,0.520,NaN,NaN,NaN,...,0.0,0.0,0.0,0.4758,0.0000,0.0,0.0,0.0037,NaN,NaN
63,2018,0.402,0.535,-3.852,3.166,JGRoberts,0.716,NaN,NaN,NaN,...,0.0,0.0,0.0,0.7161,0.0000,0.0,0.0,0.0249,0.2590,NaN
64,2019,0.355,0.571,-3.969,3.158,JGRoberts,0.784,NaN,NaN,NaN,...,0.0,0.0,0.0,0.7836,0.0000,0.0,0.0,0.0183,0.1981,NaN
65,2020,0.741,0.630,-4.070,3.050,BMKavanaugh,0.476,NaN,NaN,NaN,...,0.0,NaN,0.0,0.3522,0.0000,0.0,0.0,0.0947,0.4757,0.0774
66,2021,0.827,0.675,-4.137,3.133,BMKavanaugh,0.436,NaN,NaN,NaN,...,0.0,NaN,0.0,0.3130,0.0001,0.0,0.0,0.2007,0.4355,0.0507

In [62]:
df = df.rename(columns={'term_year': 'term'})

df.term = df.term.astype('int64')
df.head()

df_full = df.merge(martin_quinn[['term', 'med']], on='term')
df_full

,vectors,meta.case_id,meta.advocates,meta.win_side,meta.votes_side,convo_id,term,docket_id,med
0,[],1955_71,"{'harry_f_murphy': {'side': 1, 'role': 'inferr...",0,"{'j__john_m_harlan2': 0, 'j__hugo_l_black': 0,...",13127,1955,71,0.559
1,[],1955_410,"{'howard_c_westwood': {'side': 1, 'role': 'inf...",1,"{'j__john_m_harlan2': 1, 'j__hugo_l_black': 1,...",12997,1955,410,0.559
2,[],1955_410,"{'howard_c_westwood': {'side': 1, 'role': 'inf...",1,"{'j__john_m_harlan2': 1, 'j__hugo_l_black': 1,...",13024,1955,410,0.559
3,[],1955_351,"{'harry_d_graham': {'side': 3, 'role': 'inferr...",1,"{'j__john_m_harlan2': 1, 'j__hugo_l_black': 1,...",13015,1955,351,0.559
4,[],1955_38,"{'robert_n_gorman': {'side': 3, 'role': 'infer...",0,"{'j__john_m_harlan2': 0, 'j__hugo_l_black': 0,...",13016,1955,38,0.559
...,...,...,...,...,...,...,...,...,...
7812,[],2019_19-635,"{'jay_alan_sekulow': {'side': 1, 'role': 'for ...",0,"{'j__john_g_roberts_jr': 0, 'j__clarence_thoma...",24998,2019,19-635,0.355
7813,[],2019_19-46,"{'erica_l_ross': {'side': 1, 'role': 'Assistan...",0,"{'j__john_g_roberts_jr': 0, 'j__clarence_thoma...",24978,2019,19-46,0.355
7814,[],2019_19-177,"{'christopher_g_michel': {'side': 1, 'role': '...",1,"{'j__john_g_roberts_jr': 1, 'j__clarence_thoma...",24979,2019,19-177,0.355
7815,[],2019_18-1584,"{'anthony_a_yang': {'side': 1, 'role': 'for th...",1,"{'j__john_g_roberts_jr': 1, 'j__clarence_thoma...",24972,2019,18-1584,0.355
7816,[],2019_19-67,"{'eric_j_feigin': {'side': 1, 'role': 'for the...",1,"{'j__john_g_roberts_jr': 1, 'j__clarence_thoma...",24969,2019,19-67,0.355

In [63]:
df_full = df_full.rename(columns={'meta.advocates': 'advocates', 
                                  'meta.votes_side': 'votes_side',
                                  'meta.win_side': 'win_side',
                                  'meta.case_id': 'case_id',
                                  'med': 'mq_score'})

# df_full.to_csv('Outcomes_NoTranscript.csv')

In [64]:
df_full.head()

,vectors,case_id,advocates,win_side,votes_side,convo_id,term,docket_id,mq_score
0,[],1955_71,"{'harry_f_murphy': {'side': 1, 'role': 'inferr...",0,"{'j__john_m_harlan2': 0, 'j__hugo_l_black': 0,...",13127,1955,71,0.559
1,[],1955_410,"{'howard_c_westwood': {'side': 1, 'role': 'inf...",1,"{'j__john_m_harlan2': 1, 'j__hugo_l_black': 1,...",12997,1955,410,0.559
2,[],1955_410,"{'howard_c_westwood': {'side': 1, 'role': 'inf...",1,"{'j__john_m_harlan2': 1, 'j__hugo_l_black': 1,...",13024,1955,410,0.559
3,[],1955_351,"{'harry_d_graham': {'side': 3, 'role': 'inferr...",1,"{'j__john_m_harlan2': 1, 'j__hugo_l_black': 1,...",13015,1955,351,0.559
4,[],1955_38,"{'robert_n_gorman': {'side': 3, 'role': 'infer...",0,"{'j__john_m_harlan2': 0, 'j__hugo_l_black': 0,...",13016,1955,38,0.559

In [67]:
"""
Writes transcripts to folder path in the form {convo_id}_{case_id}
Resulting folder is roughly 1 GB. Tread lightly. 
"""

folder_path = '/Users/quinn/Documents/GradSchool/Spring2023/INFO251/MLFinalProject/Trancripts_Case_Convo/'

# for index, row in df_full.iterrows():
#     convo_id = row['convo_id']
#     case_id = row['case_id']
    
#     file_name = convo_id+'_'+case_id+'.txt'
#     write_path = folder_path+file_name
#     transcript = get_transcript(convo_id)
    
#     text_file = open(write_path, 'w')
    
#     text_file.write(transcript)
#     text_file.close()